xread
'TNT data for Graph 0 generated by PhylogeneticGraph (PhyG)
	Source characters:
		0-159 : chel-16.fas#0
'
160 4
Americhernus	T C G A G C C T C C A A T - G A T - A C G T T G A A A G G C G T T T A - T - - - - - C - - G T T G - G G G C - C G A C A G C G C G T C G T G G G C T C G G T T G G C C T T A A - A A A G C T G A T C G G G T T C T C C G G C A A T T T T A C T T T G A A A A A A T T A G G G T G C T C A A A G C A G G C C T G - - - - G T G C C 
Artemia	C T - C G - G T C G G G T - G G T G C C G C C T C A C G G T G G T C A C T G - - C - C T C G A T C - G G A C A A T T C A T T G G A T C G T - - T C G G G G - T G C T C T T A A C C G A G - T G T C C T G G G T G G C C G A T A C G T T T A C T T T G A A C A A A T T A G A G T G C T T A A A G C A - G - G T G C A C C G C G C C 
Gea	T C - C G - G C C G G A C G G G T - C C G C C T A C C G G T G G T T A C T G T T C G C T - - G C C - G A G C - - T T C A G G G G G C C G C - - T G T C G A - T G A T C T T C A T C G G T - T A T C T T C C G T A A C C C T C A C G T T T A C T T T G A A A A A A T T A G A G T G C T C A A A G C A - G C G C G - A - - - C G C C 
Hypochilus	T C - C A - G A C G G G C - G G T - C C G C C T A A C G G T G G T T A C T G - - C - C T - G G C C T G A A C - A A C C A G C C G G T T T C - - C C T A G A - T G A T C T T C A T T G A T - T G T C T T G G G T G A C C G G C A C G T T T A C T T T G A A A A A A T T A G A G T G C T C A A A G C A - G C G T G - A - - - C G C C 
;
cc - 0.159;
proc/;

